[package]
name = "coq-of-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty = "0.11.3"

[package.metadata.rust-analyzer]
rustc_private=true
